"""initial schema

Revision ID: 6692d0e978f4
Revises: 
Create Date: 2026-06-30 21:06:21.305797
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import app.core.types

# revision identifiers, used by Alembic.
revision: str = '6692d0e978f4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('federations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=20), nullable=True),
    sa.Column('settings', app.core.types.JSONType(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('federations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_federations_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_federations_slug'), ['slug'], unique=True)

    op.create_table('roles',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('permissions', app.core.types.JSONType(), nullable=True),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('event_categories',
    sa.Column('federation_id', app.core.types.GUID(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('discipline', sa.Enum('singles', 'doubles', name='discipline', native_enum=False, length=40), nullable=False),
    sa.Column('gender_scope', sa.Enum('men', 'women', 'mixed', 'any', name='genderscope', native_enum=False, length=40), nullable=False),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['federation_id'], ['federations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('federation_id', 'code', name='uq_category_federation_code')
    )
    with op.batch_alter_table('event_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_categories_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_categories_federation_id'), ['federation_id'], unique=False)

    op.create_table('state_associations',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=40), nullable=True),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('federation_id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['federation_id'], ['federations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('federation_id', 'name', name='uq_state_federation_name')
    )
    with op.batch_alter_table('state_associations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_state_associations_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_state_associations_federation_id'), ['federation_id'], unique=False)

    op.create_table('clubs',
    sa.Column('state_id', app.core.types.GUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('coach_name', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=40), nullable=True),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('federation_id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['federation_id'], ['federations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['state_id'], ['state_associations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('federation_id', 'name', name='uq_club_federation_name')
    )
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clubs_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_clubs_federation_id'), ['federation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clubs_state_id'), ['state_id'], unique=False)

    op.create_table('ranking_rules',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('level', sa.Enum('national_championship', 'open', 'invitational', 'ranking', name='tournamentlevel', native_enum=False, length=40), nullable=False),
    sa.Column('category_id', app.core.types.GUID(), nullable=True),
    sa.Column('config', app.core.types.JSONType(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('federation_id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['event_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['federation_id'], ['federations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ranking_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ranking_rules_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ranking_rules_federation_id'), ['federation_id'], unique=False)

    op.create_table('players',
    sa.Column('federation_player_code', sa.String(length=40), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('gender', sa.Enum('M', 'F', 'O', name='gender', native_enum=False, length=40), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=80), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', 'retired', name='playerstatus', native_enum=False, length=40), nullable=False),
    sa.Column('club_id', app.core.types.GUID(), nullable=True),
    sa.Column('state_id', app.core.types.GUID(), nullable=True),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('federation_id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['federation_id'], ['federations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['state_id'], ['state_associations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('federation_id', 'federation_player_code', name='uq_player_federation_code')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_club_id'), ['club_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_federation_id'), ['federation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_federation_player_code'), ['federation_player_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_state_id'), ['state_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_status'), ['status'], unique=False)

    op.create_table('ranking_points',
    sa.Column('rule_id', app.core.types.GUID(), nullable=False),
    sa.Column('result_key', sa.String(length=40), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('federation_id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['federation_id'], ['federations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['ranking_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'result_key', name='uq_points_rule_result')
    )
    with op.batch_alter_table('ranking_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ranking_points_federation_id'), ['federation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ranking_points_rule_id'), ['rule_id'], unique=False)

    op.create_table('tournaments',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('level', sa.Enum('national_championship', 'open', 'invitational', 'ranking', name='tournamentlevel', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('draft', 'registration_open', 'registration_closed', 'ongoing', 'completed', name='tournamentstatus', native_enum=False, length=40), nullable=False),
    sa.Column('organizer', sa.String(length=200), nullable=True),
    sa.Column('ranking_rule_id', app.core.types.GUID(), nullable=True),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('federation_id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['federation_id'], ['federations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ranking_rule_id'], ['ranking_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournaments_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournaments_federation_id'), ['federation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournaments_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournaments_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournaments_status'), ['status'], unique=False)

    op.create_table('events',
    sa.Column('tournament_id', app.core.types.GUID(), nullable=False),
    sa.Column('category_id', app.core.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('draw_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'draw_published', 'ongoing', 'completed', name='eventstatus', native_enum=False, length=40), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('federation_id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['event_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['federation_id'], ['federations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'category_id', name='uq_event_tournament_category')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_federation_id'), ['federation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_tournament_id'), ['tournament_id'], unique=False)

    op.create_table('player_stats',
    sa.Column('player_id', app.core.types.GUID(), nullable=False),
    sa.Column('category_id', app.core.types.GUID(), nullable=True),
    sa.Column('matches_played', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('titles', sa.Integer(), nullable=False),
    sa.Column('finals', sa.Integer(), nullable=False),
    sa.Column('semi_finals', sa.Integer(), nullable=False),
    sa.Column('win_percentage', sa.Float(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('federation_id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['event_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['federation_id'], ['federations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'category_id', name='uq_stats_player_category')
    )
    with op.batch_alter_table('player_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_stats_federation_id'), ['federation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_stats_player_id'), ['player_id'], unique=False)

    op.create_table('ranking_history',
    sa.Column('player_id', app.core.types.GUID(), nullable=False),
    sa.Column('category_id', app.core.types.GUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('previous_rank', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('movement', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('federation_id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['event_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['federation_id'], ['federations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ranking_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ranking_history_federation_id'), ['federation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ranking_history_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ranking_history_snapshot_date'), ['snapshot_date'], unique=False)

    op.create_table('rankings',
    sa.Column('player_id', app.core.types.GUID(), nullable=False),
    sa.Column('category_id', app.core.types.GUID(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('previous_rank', sa.Integer(), nullable=True),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('imported', 'computed', name='rankingsource', native_enum=False, length=40), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('federation_id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['event_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['federation_id'], ['federations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('federation_id', 'player_id', 'category_id', 'as_of', name='uq_ranking_player_category_date')
    )
    with op.batch_alter_table('rankings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rankings_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_rankings_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rankings_federation_id'), ['federation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rankings_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rankings_rank'), ['rank'], unique=False)

    op.create_table('users',
    sa.Column('federation_id', app.core.types.GUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('player_id', app.core.types.GUID(), nullable=True),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['federation_id'], ['federations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('federation_id', 'email', name='uq_users_federation_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_federation_id'), ['federation_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('federation_id', app.core.types.GUID(), nullable=True),
    sa.Column('actor_user_id', app.core.types.GUID(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('before', app.core.types.JSONType(), nullable=True),
    sa.Column('after', app.core.types.JSONType(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['federation_id'], ['federations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_federation_created', ['federation_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)

    op.create_table('matches',
    sa.Column('event_id', app.core.types.GUID(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('player1_id', app.core.types.GUID(), nullable=True),
    sa.Column('player2_id', app.core.types.GUID(), nullable=True),
    sa.Column('winner_id', app.core.types.GUID(), nullable=True),
    sa.Column('score', app.core.types.JSONType(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'in_progress', 'completed', 'walkover', 'bye', name='matchstatus', native_enum=False, length=40), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_match_id', app.core.types.GUID(), nullable=True),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('federation_id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['federation_id'], ['federations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['next_match_id'], ['matches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player1_id'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player2_id'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['winner_id'], ['players.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_federation_id'), ['federation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_round'), ['round'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_status'), ['status'], unique=False)

    op.create_table('notifications',
    sa.Column('user_id', app.core.types.GUID(), nullable=True),
    sa.Column('channel', sa.Enum('email', 'sms', 'push', name='notificationchannel', native_enum=False, length=40), nullable=False),
    sa.Column('template', sa.String(length=120), nullable=False),
    sa.Column('payload', app.core.types.JSONType(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'sent', 'failed', name='notificationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('federation_id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['federation_id'], ['federations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_federation_id'), ['federation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('user_id', app.core.types.GUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('family_id', app.core.types.GUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('registrations',
    sa.Column('event_id', app.core.types.GUID(), nullable=False),
    sa.Column('player_id', app.core.types.GUID(), nullable=False),
    sa.Column('partner_player_id', app.core.types.GUID(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'withdrawn', 'rejected', name='registrationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('federation_id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['federation_id'], ['federations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_player_id'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'player_id', name='uq_registration_event_player')
    )
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registrations_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_federation_id'), ['federation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_player_id'), ['player_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', app.core.types.GUID(), nullable=False),
    sa.Column('role_id', app.core.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registrations_player_id'))
        batch_op.drop_index(batch_op.f('ix_registrations_federation_id'))
        batch_op.drop_index(batch_op.f('ix_registrations_event_id'))
        batch_op.drop_index(batch_op.f('ix_registrations_deleted_at'))

    op.drop_table('registrations')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_family_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_federation_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_status'))
        batch_op.drop_index(batch_op.f('ix_matches_round'))
        batch_op.drop_index(batch_op.f('ix_matches_federation_id'))
        batch_op.drop_index(batch_op.f('ix_matches_event_id'))
        batch_op.drop_index(batch_op.f('ix_matches_deleted_at'))

    op.drop_table('matches')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index('ix_audit_federation_created')

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_federation_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_deleted_at'))

    op.drop_table('users')
    with op.batch_alter_table('rankings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rankings_rank'))
        batch_op.drop_index(batch_op.f('ix_rankings_player_id'))
        batch_op.drop_index(batch_op.f('ix_rankings_federation_id'))
        batch_op.drop_index(batch_op.f('ix_rankings_category_id'))
        batch_op.drop_index(batch_op.f('ix_rankings_as_of'))

    op.drop_table('rankings')
    with op.batch_alter_table('ranking_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ranking_history_snapshot_date'))
        batch_op.drop_index(batch_op.f('ix_ranking_history_player_id'))
        batch_op.drop_index(batch_op.f('ix_ranking_history_federation_id'))

    op.drop_table('ranking_history')
    with op.batch_alter_table('player_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_stats_player_id'))
        batch_op.drop_index(batch_op.f('ix_player_stats_federation_id'))

    op.drop_table('player_stats')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_tournament_id'))
        batch_op.drop_index(batch_op.f('ix_events_federation_id'))
        batch_op.drop_index(batch_op.f('ix_events_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_events_category_id'))

    op.drop_table('events')
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournaments_status'))
        batch_op.drop_index(batch_op.f('ix_tournaments_start_date'))
        batch_op.drop_index(batch_op.f('ix_tournaments_name'))
        batch_op.drop_index(batch_op.f('ix_tournaments_federation_id'))
        batch_op.drop_index(batch_op.f('ix_tournaments_deleted_at'))

    op.drop_table('tournaments')
    with op.batch_alter_table('ranking_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ranking_points_rule_id'))
        batch_op.drop_index(batch_op.f('ix_ranking_points_federation_id'))

    op.drop_table('ranking_points')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_status'))
        batch_op.drop_index(batch_op.f('ix_players_state_id'))
        batch_op.drop_index(batch_op.f('ix_players_full_name'))
        batch_op.drop_index(batch_op.f('ix_players_federation_player_code'))
        batch_op.drop_index(batch_op.f('ix_players_federation_id'))
        batch_op.drop_index(batch_op.f('ix_players_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_players_club_id'))

    op.drop_table('players')
    with op.batch_alter_table('ranking_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ranking_rules_federation_id'))
        batch_op.drop_index(batch_op.f('ix_ranking_rules_deleted_at'))

    op.drop_table('ranking_rules')
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clubs_state_id'))
        batch_op.drop_index(batch_op.f('ix_clubs_federation_id'))
        batch_op.drop_index(batch_op.f('ix_clubs_deleted_at'))

    op.drop_table('clubs')
    with op.batch_alter_table('state_associations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_state_associations_federation_id'))
        batch_op.drop_index(batch_op.f('ix_state_associations_deleted_at'))

    op.drop_table('state_associations')
    with op.batch_alter_table('event_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_categories_federation_id'))
        batch_op.drop_index(batch_op.f('ix_event_categories_deleted_at'))

    op.drop_table('event_categories')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    with op.batch_alter_table('federations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_federations_slug'))
        batch_op.drop_index(batch_op.f('ix_federations_deleted_at'))

    op.drop_table('federations')
    # ### end Alembic commands ###
