"""ranking_awards ledger

Revision ID: 7bfaa7427765
Revises: 6692d0e978f4
Create Date: 2026-07-09 22:54:32.616141
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import app.core.types

# revision identifiers, used by Alembic.
revision: str = '7bfaa7427765'
down_revision: str | None = '6692d0e978f4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranking_awards',
    sa.Column('player_id', app.core.types.GUID(), nullable=False),
    sa.Column('category_id', app.core.types.GUID(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('imported', 'computed', name='rankingsource', native_enum=False, length=40), nullable=False),
    sa.Column('tournament_id', app.core.types.GUID(), nullable=True),
    sa.Column('event_id', app.core.types.GUID(), nullable=True),
    sa.Column('result_key', sa.String(length=40), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('awarded_on', sa.Date(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('federation_id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['event_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['federation_id'], ['federations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ranking_awards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ranking_awards_awarded_on'), ['awarded_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_ranking_awards_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ranking_awards_federation_id'), ['federation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ranking_awards_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ranking_awards_tournament_id'), ['tournament_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ranking_awards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ranking_awards_tournament_id'))
        batch_op.drop_index(batch_op.f('ix_ranking_awards_player_id'))
        batch_op.drop_index(batch_op.f('ix_ranking_awards_federation_id'))
        batch_op.drop_index(batch_op.f('ix_ranking_awards_category_id'))
        batch_op.drop_index(batch_op.f('ix_ranking_awards_awarded_on'))

    op.drop_table('ranking_awards')
    # ### end Alembic commands ###
